### ISSUE TITLE
SyntaxError: Unexpected token u at pub.coffee L41:8

### ISSUE THREAD

**Issue by sunny-g** [ccorcos/meteor-any-db#5]
Here's the code:

``` js
AnyDb.publish('mongoUsers', function() {
  return Users.find({}, {sort: {age: -1}}).fetch();
});

addMongoUser = function(name, age) {
  var user = Users.insert({name: name, age: age});
  AnyDb.refresh('mongoUsers', true);
  return user;
};

removeMongoUsers = function(name) {
  if (!name) {
    Users.remove({});
  } else {
    Users.remove({name: name});        
  }
  AnyDb.refresh('mongoUsers', true);
  return;
};
```

and here's the stack trace:

```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at U.deserialize (packages/ccorcos_utils/utils.coffee:12:32)
    at Array.map (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:448:1)
    at Object.AnyDb.refresh (packages/ccorcos_any-db/pub.coffee:41:8)
    at addMongoUser (neo4j-fibers.js:35:13)
    at [object Object]:1:-61
    at Script.(anonymous function) [as runInThisContext] (vm.js:41:22)
    at /Users/sunnygonnabathula/gitdev/neo4j-fibers/web/.meteor/local/build/programs/server/shell-server.js:305:27
    at /Users/sunnygonnabathula/.meteor/packages/meteor-tool/.1.1.10.1quijed++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40
```

It occurs when calling the `addMongoUser` function from `meteor shell` regardless of whether or not there are documents in Mongo already.

**Comment by ccorcos** [comment]
The second argument to AnyDb.refresh is a filter function to filter through the AnyDb.publish queries. If you want to refresh all publications, try `R.T` or `R.always(true)` or `function() {return true}`

**Comment by sunny-g** [comment]
Hmm I changed that and the error is still occurring.

After a little debugging, I realized that having not specifying a query in the subscription creates an object that looks like this for `AnyDb.pubs.allMongoUsers`:

```
{ undefined:
   { '1':
      { subId: '1',
        docs: [Object],
        name: 'allMongoUsers',
        query: undefined,
        fetch: [Function],
        observer: [Object],
        refresh: [Function],
        transform: [Function] } } }
```

Running `JSON.parse('undefined')` is what's throwing the error. What should be passed into `AnyDb.subscribe` as a query if you don't have one to specify?

**Comment by ccorcos** [comment]
`{}`

**Comment by sunny-g** [comment]
Perfect, thanks!
